export { default as HeroSection } from "./HeroSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as PricingSection } from "./PricingSection";
export { default as RewardsSection } from "./RewardsSection";
export { default as CTASection } from "./CTASection";
export { default as MannmitraIntro } from "./MannmitraIntro";
export { default as FAQSection } from "./FAQSection";
export { default as ContactSection } from "./ContactSection";
export { default as Testimonials } from "./Testimonials";